websites = {
    'Macaroni & Cheese': ['https://www.momontimeout.com/best-homemade-baked-mac-and-cheese-recipe/'],
    'Cheese Sticks': ['https://www.tasteofhome.com/recipes/mozzarella-sticks/'],
    'Cheese Bread': ['https://sallysbakingaddiction.com/homemade-cheese-bread/'],
    'Baked Bread Sticks': ['https://sallysbakingaddiction.com/homemade-breadsticks/'],
    'Cheese Quesadillas': ['https://www.simplyrecipes.com/recipes/quesadilla/'],
    'Chicken & Cheese Quesadillas': ['https://www.foodnetwork.com/recipes/chicken-quesadillas-recipe/'],
    'Meat & Cheese Quesadillas': ['https://girlheartfood.com/cheesy-ground-beef-quesadillas/'],
    'Ham & Cheese Sandwich': ['https://insanelygoodrecipes.com/grilled-ham-and-cheese-sandwich/'],
    'Bacon & Cheese Sandwich': ['https://www.spendwithpennies.com/bacon-grilled-cheese/'],
    'BLT Sandwich': ['https://thefoodcharlatan.com/b-l-a-t-bacon-lettuce-avocado-tomato-sandwich-with-aioli-sauce-and-feta/'],
    'Fish Sandwich': ['https://www.billyparisi.com/fish-sandwich/'],
    'Turkey Sandwich': ['https://anourishingplate.com/turkey-club-sandwich/'],
    'Turkey Sandwich w/Cheese': ['https://www.favfamilyrecipes.com/turkey-sandwich/'],
    'Sausage & Egg Muffin': ['https://ameessavorydish.com/sausage-egg-muffins/'],
    'Scrambled Eggs': ['https://www.loveandlemons.com/scrambled-eggs-recipe/'],
    'Cheesy Scrambled Eggs': ['https://www.bonappetit.com/recipe/soft-scrambled-eggs-with-fresh-ricotta-and-chives'],
    'Sunny Side Eggs': ['https://www.loveandlemons.com/sunny-side-up-eggs/'],
    'Omelette': ['https://www.loveandlemons.com/omelette-recipe/'],
    'Hot Dogs': ['https://thepennywisemama.com/new-york-hot-dog-recipe/'],
    'Chili Cheese Dogs': ['https://www.tasteofhome.com/recipes/chili-dogs/'],
    'Tacos': ['https://feelgoodfoodie.net/recipe/ground-beef-tacos-napa-cabbage-guacamole/'],
    'Tacos w/Chicken': ['https://damndelicious.net/2019/08/06/easy-chicken-tacos/'],
    'Taco Salad': ['https://www.foodnetwork.com/recipes/taco-salad-recipe/'],
    'Grilled Chicken Salad': ['https://www.tasteofhome.com/recipes/grilled-chicken-salad/'],
    'Grilled Chicken Avocado Salad': ['https://www.honeyandbirch.com/grilled-chicken-avocado-salad/'],
    'Grilled Cheese': ['https://www.allrecipes.com/recipe/23891/grilled-cheese-sandwich/'],
    'French Toast': ['https://www.allrecipes.com/recipe/7016/french-toast-i/'],
    'Burger': ['https://www.aspicyperspective.com/best-hamburger-patty-recipe/'],
    'Cheese Burger': ['https://www.recipetineats.com/cheeseburger-recipe/'],
    'Pasta': ['https://www.allrecipes.com/recipe/21455/quick-pasta-sauce/'],
    'Pasta w/Meat': ['https://www.allrecipes.com/recipe/158140/spaghetti-sauce-with-ground-beef/'],
    'Spaghetti': ['https://www.allrecipes.com/recipe/21455/quick-pasta-sauce/'],
    'Alfredo': ['https://www.allrecipes.com/recipe/23431/to-die-for-fettuccine-alfredo/'],
    'Chicken Alfredo': ['https://www.tasteofhome.com/recipes/easy-chicken-alfredo/'],
    'Shrimp Scampi Linguine': ['https://www.foodnetwork.com/recipes/tyler-florence/shrimp-scampi-with-linguini-recipe-1942429'],
    'Chicken & Rice Combination': ['https://www.recipetineats.com/oven-baked-chicken-and-rice/'],
    'Ice Cream Shake Drink': ['https://www.allrecipes.com/recipe/48974/vanilla-milkshake-i/'],
    'Baked potato': ['https://www.loveandlemons.com/baked-potato/'],
    'French Fries': ['https://www.recipetineats.com/french-fries/'],
    'Cheesy Baked potato': ['https://www.food.com/recipe/easy-cheddar-potato-bake-72139'],
    'Chili': ['https://www.allrecipes.com/recipe/16248/easy-homemade-chili/'],
    'Chili Cheese French Fries': ['https://www.dinneratthezoo.com/chili-cheese-fries/'],
    'Chili w/Beans': ['https://www.spendwithpennies.com/the-best-chili-recipe/#wprm-recipe-container-145347'],
    'Pizza': ['https://www.loveandlemons.com/homemade-pizza/'],
    'Pepperoni Pizza': ['https://www.simplyrecipes.com/recipes/homemade_pepperoni_pizza/'],
    'Pizza w/Meat': ['https://www.bakedbyrachel.com/meat-lovers-pizza/'],
    'Pizza w/Chicken': ['https://foxeslovelemons.com/grilled-chicken-pizza/'],
    'Nachos w/Meat': ['https://www.allrecipes.com/loaded-beef-nachos-recipe-7489045'],
    'Nachos w/Chicken': ['https://www.recipetineats.com/chicken-nachos-recipe/'],
    'Nachos w/Cheese': ['https://www.spendwithpennies.com/easy-cheesy-nachos/'],
    'Ice Cream Sandwiches': ['https://www.allrecipes.com/recipe/284548/classic-chocolate-ice-cream-sandwich/'],
    'Smore Sandwiches': ['https://www.simplyrecipes.com/recipes/smores/'],
    'Fruit Salad': ['https://www.allrecipes.com/recipe/214947/perfect-summer-fruit-salad/'],
    'Fruit Smoothie': ['https://www.foodnetwork.com/recipes/fruit-smoothie-recipe/'],
    'Caesar Salad': ['https://www.simplyrecipes.com/recipes/caesar_salad/'],
    'Caprese Salad': ['https://www.tasteofhome.com/recipes/caprese-salad/'],
    'Grilled Shrimp': ['https://feelgoodfoodie.net/recipe/grilled-shrimp-skewers/'],
    'Margarita Pizza': ['https://www.abeautifulplate.com/the-best-homemade-margherita-pizza/'],
    'Vegetable Stir-Fry': ['https://therecipecritic.com/vegetable-stir-fry/'],
    'Spicy Tofu Curry': ['https://www.indianhealthyrecipes.com/tofu-curry/'],
    'Homemade Lasagna': ['https://www.allrecipes.com/recipe/23600/worlds-best-lasagna/'],
    'Sushi Rolls': ['https://www.justonecookbook.com/california-roll/'],
    'Spinach and Feta Stuffed Chicken': ['https://feelgoodfoodie.net/recipe/spinach-feta-stuffed-chicken/'],
    'Mango Salsa': ['https://cookieandkate.com/fresh-mango-salsa-recipe/'],
    'Avocado Toast': ['https://cookieandkate.com/avocado-toast-recipe/'],
    'Chocolate Chip Cookies': ['https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/'],
    'Fruit Smoothie Bowl': ['https://minimalistbaker.com/favorite-smoothie-bowl-5-minutes/'],
    'Pancakes': ['https://www.allrecipes.com/recipe/21014/good-old-fashioned-pancakes/'],
    'Greek Salad': ['https://www.loveandlemons.com/greek-salad/'],
    'Hawaiian Pizza': ['https://sallysbakingaddiction.com/hawaiian-pizza/'],
    'Crispy Chicken Tenders': ['https://feastandfarm.com/crispy-fried-chicken-tenders/'],
    'Garlic Butter Shrimp': ['https://www.dinneratthezoo.com/garlic-butter-shrimp/'],
    'Caprese Pasta Salad': ['https://www.asouthernsoul.com/best-caprese-pasta-salad-fresh-and-easy/'],
    'Veggie Burger': ['https://www.loveandlemons.com/best-veggie-burger-recipe/'],
    'Lemonade': ['https://www.allrecipes.com/recipe/32385/best-lemonade-ever/'],
    'Cucumber Dill Salad': ['https://www.loveandlemons.com/cucumber-salad/'],
    'Tofu Scramble': ['https://www.noracooks.com/tofu-scramble/'],
    'Cauliflower Rice': ['https://www.loveandlemons.com/how-to-make-cauliflower-rice/'],
    'Pulled Pork Sandwich': ['https://www.melskitchencafe.com/bbq-pulled-pork-sandwiches-slow-cooker/'],
    'Shrimp and Grits': ['https://www.foodnetwork.com/recipes/shrimp-and-grits-recipe/'],
    'Ratatouille': ['https://www.howtocook.recipes/homemade-ratatouille-recipe/'],
    'Stuffed Bell Peppers': ['https://www.allrecipes.com/recipe/16330/stuffed-peppers/'],
    'Garlic Knots': ['https://www.simplyrecipes.com/recipes/garlic_knots/'],
    'Peanut Butter and Jelly Sandwich': ['https://www.food.com/recipe/traditional-peanut-butter-and-jelly-243965'],
    'Vegetable Omelette': ['https://www.liveeatlearn.com/how-to-make-an-omelette/'],
    'Pasta with Garlic and Olive Oil': ['https://theclevermeal.com/spaghetti-garlic-olive-oil/'],
    'Fried Rice': ['https://www.gimmesomeoven.com/fried-rice-recipe/'],
    'Tomato Soup': ['https://www.allrecipes.com/recipe/39544/garden-fresh-tomato-soup/'],
    'Mashed Potatoes': ['https://www.simplyrecipes.com/recipes/mashed_potatoes/'],
    'Classic BLT Sandwich': ['https://www.food.com/recipe/classic-blt-sandwich-129615'],
    'Oatmeal': ['https://feelgoodfoodie.net/recipe/how-to-make-oatmeal/'],
    'Chicken Noodle Soup': ['https://www.simplyrecipes.com/recipes/chicken_noodle_soup/'],
    'Greek Salad': ['https://www.loveandlemons.com/greek-salad/'],
    'Cake': ['https://www.allrecipes.com/recipe/17481/simple-white-cake/'],
    'Brownies': ['https://www.inspiredtaste.net/24412/cocoa-brownies-recipe/'],
    'Meatballs': ['https://www.iheartnaptime.net/meatball-recipe/#recipe']
}
