websites = {
    'Macaroni & Cheese': ['https://www.momontimeout.com/best-homemade-baked-mac-and-cheese-recipe/'],
    'Cheese Sticks': ['https://www.tasteofhome.com/recipes/mozzarella-sticks/'],
    'Cheese Bread': ['https://www.allrecipes.com/recipe/15165/cheese-bread/'],
    'Baked Bread Sticks': ['https://www.tasteofhome.com/recipes/soft-breadsticks/'],
    'Cheese Quesadillas': ['https://www.simplyrecipes.com/recipes/quesadilla/'],
    'Chicken & Cheese Quesadillas': ['https://www.foodnetwork.com/recipes/chicken-quesadillas-recipe/'],
    'Meat & Cheese Quesadillas': ['https://www.allrecipes.com/recipe/16501/beef-quesadillas/'],
    'Ham & Cheese Sandwich': ['https://www.allrecipes.com/recipe/256452/classic-ham-and-cheese-sandwich/'],
    'Bacon & Cheese Sandwich': ['https://www.tasteofhome.com/recipes/bacon-grilled-cheese-sandwiches/'],
    'BLT Sandwich': ['https://www.delish.com/cooking/recipe-ideas/a19665827/best-blt-recipe/'],
    'Fish Sandwich': ['https://www.allrecipes.com/recipe/161850/chef-johns-crispy-fish-sandwich/'],
    'Turkey Sandwich': ['https://www.delish.com/cooking/recipe-ideas/a19666447/turkey-sandwich-recipe/'],
    'Turkey Sandwich w/Cheese': ['https://www.tasteofhome.com/recipes/turkey-and-cheese-panini/'],
    'Sausage & Egg Muffin': ['https://www.foodnetwork.com/recipes/sausage-egg-and-cheese-muffin-sandwich-recipe/'],
    'Scrambled Eggs': ['https://www.loveandlemons.com/scrambled-eggs-recipe/'],
    'Cheesy Scrambled Eggs': ['https://www.allrecipes.com/recipe/232738/creamy-cheesy-scrambled-eggs/'],
    'Sunny Side Eggs': ['https://www.allrecipes.com/recipe/245003/sunny-side-up-eggs/'],
    'Omelette': ['https://www.foodnetwork.com/recipes/basic-omelette-recipe/'],
    'Hot Dogs': ['https://www.foodnetwork.com/recipes/classic-grilled-hot-dogs-recipe/'],
    'Chili Cheese Dogs': ['https://www.tasteofhome.com/recipes/chili-dogs/'],
    'Tacos': ['https://www.delish.com/cooking/recipe-ideas/a27752703/easy-beef-tacos-recipe/'],
    'Tacos w/Chicken': ['https://www.simplyrecipes.com/recipes/chicken_tacos/'],
    'Taco Salad': ['https://www.foodnetwork.com/recipes/taco-salad-recipe/'],
    'Grilled Chicken Salad': ['https://www.tasteofhome.com/recipes/grilled-chicken-salad/'],
    'Grilled Chicken Avocado Salad': ['https://www.eatwell101.com/grilled-chicken-avocado-salad-recipe/'],
    'Grilled Cheese': ['https://www.allrecipes.com/recipe/23891/grilled-cheese-sandwich/'],
    'French Toast': ['https://www.allrecipes.com/recipe/7016/french-toast-i/'],
    'Burger': ['https://www.foodnetwork.com/recipes/classic-burger-recipe/'],
    'Cheese Burger': ['https://www.delish.com/cooking/recipe-ideas/a19665882/classic-cheeseburger-recipe/'],
    'Pasta': ['https://www.allrecipes.com/recipe/23431/penne-pasta-with-marinara/'],
    'Pasta w/Meat': ['https://www.simplyrecipes.com/recipes/spaghetti_with_meat_sauce/'],
    'Spaghetti': ['https://www.allrecipes.com/recipe/158140/spaghetti-sauce-with-ground-beef/'],
    'Alfredo': ['https://www.allrecipes.com/recipe/23431/quick-and-easy-alfredo-sauce/'],
    'Chicken Alfredo': ['https://www.tasteofhome.com/recipes/easy-chicken-alfredo/'],
    'Shrimp Scampi Linguine': ['https://www.foodnetwork.com/recipes/shrimp-scampi-recipe/'],
    'Chicken & Rice Combination': ['https://www.simplyrecipes.com/recipes/one_pot_chicken_and_rice/'],
    'Ice Cream Shake Drink': ['https://www.allrecipes.com/recipe/233928/perfect-milkshake/'],
    'Baked potato': ['https://www.allrecipes.com/recipe/85330/awesome-baked-potato/'],
    'French Fries': ['https://www.foodnetwork.com/recipes/classic-french-fries-recipe/'],
    'Cheesy Baked potato': ['https://www.tasteofhome.com/recipes/cheesy-baked-potatoes/'],
    'Chili': ['https://www.foodnetwork.com/recipes/classic-chili-recipe/'],
    'Chili Cheese French Fries': ['https://www.allrecipes.com/recipe/233731/chili-cheese-fries/'],
    'Chili w/Beans': ['https://www.simplyrecipes.com/recipes/beef_chili_with_beans/'],
    'Pizza': ['https://www.simplyrecipes.com/recipes/how_to_make_perfect_pizza/'],
    'Pepperoni Pizza': ['https://www.allrecipes.com/recipe/23431/perfect-pepperoni-pizza/'],
    'Pizza w/Meat': ['https://www.bakedbyrachel.com/meat-lovers-pizza/'],
    'Pizza w/Chicken': ['https://www.simplyrecipes.com/recipes/bbq_chicken_pizza/'],
    'Nachos w/Meat': ['https://www.delish.com/cooking/recipe-ideas/a28848400/nachos-supreme-recipe/'],
    'Nachos w/Chicken': ['https://www.allrecipes.com/recipe/216759/easy-chicken-nachos/'],
    'Nachos w/Cheese': ['https://www.tasteofhome.com/recipes/easy-cheesy-nachos/'],
    'Ice Cream Sandwiches': ['https://www.allrecipes.com/recipe/237462/homemade-ice-cream-sandwiches/'],
    'Smore Sandwiches': ['https://www.simplyrecipes.com/recipes/smores/'],
    'Fruit Salad': ['https://www.allrecipes.com/recipe/214947/perfect-summer-fruit-salad/'],
    'Fruit Smoothie': ['https://www.foodnetwork.com/recipes/fruit-smoothie-recipe/'],
    'Caesar Salad': ['https://www.simplyrecipes.com/recipes/caesar_salad/'],
    'Caprese Salad': ['https://www.tasteofhome.com/recipes/caprese-salad/'],
    'Grilled Shrimp': ['https://www.foodnetwork.com/recipes/grilled-shrimp-recipe/'],
    'Margarita Pizza': ['https://www.simplyrecipes.com/recipes/margherita_pizza/'],
    'Vegetable Stir-Fry': ['https://www.allrecipes.com/recipe/228823/quick-and-easy-vegetable-stir-fry/'],
    'Spicy Tofu Curry': ['https://www.tasteofhome.com/recipes/tofu-curry/'],
    'Homemade Lasagna': ['https://www.allrecipes.com/recipe/23600/worlds-best-lasagna/'],
    'Sushi Rolls': ['https://www.justonecookbook.com/california-roll/'],
    'Spinach and Feta Stuffed Chicken': ['https://www.allrecipes.com/recipe/236617/spinach-and-feta-stuffed-chicken-breast/'],
    'Mango Salsa': ['https://www.allrecipes.com/recipe/214210/mango-salsa/'],
    'Avocado Toast': ['https://www.foodnetwork.com/recipes/avocado-toast-recipe/'],
    'Chocolate Chip Cookies': ['https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/'],
    'Fruit Smoothie Bowl': ['https://www.foodnetwork.com/recipes/fruit-smoothie-bowl-recipe/'],
    'Pancakes': ['https://www.simplyrecipes.com/recipes/fluffy_pancakes/'],
    'Greek Salad': ['https://www.allrecipes.com/recipe/14469/greek-salad/'],
    'Hawaiian Pizza': ['https://www.simplyrecipes.com/recipes/hawaiian_pizza/'],
    'Crispy Chicken Tenders': ['https://www.allrecipes.com/recipe/237821/crispy-chicken-tenders/'],
    'Garlic Butter Shrimp': ['https://www.delish.com/cooking/recipe-ideas/a19665846/garlic-butter-shrimp-recipe/'],
    'Caprese Pasta Salad': ['https://www.allrecipes.com/recipe/273808/caprese-pasta-salad/'],
    'Veggie Burger': ['https://www.simplyrecipes.com/recipes/veggie_burger/'],
    'Lemonade': ['https://www.allrecipes.com/recipe/32385/best-lemonade-ever/'],
    'Cucumber Dill Salad': ['https://www.simplyrecipes.com/recipes/cucumber_salad_with_dill/'],
    'Tofu Scramble': ['https://www.allrecipes.com/recipe/236316/tofu-scramble/'],
    'Cauliflower Rice': ['https://www.simplyrecipes.com/recipes/cauliflower_rice/'],
    'Pulled Pork Sandwich': ['https://www.melskitchencafe.com/bbq-pulled-pork-sandwiches-slow-cooker/'],
    'Shrimp and Grits': ['https://www.foodnetwork.com/recipes/shrimp-and-grits-recipe/'],
    'Ratatouille': ['https://www.simplyrecipes.com/recipes/ratatouille/'],
    'Stuffed Bell Peppers': ['https://www.allrecipes.com/recipe/16330/stuffed-peppers/'],
    'Garlic Knots': ['https://www.simplyrecipes.com/recipes/garlic_knots/'],
    'Peanut Butter and Jelly Sandwich': ['https://www.foodnetwork.com/recipes/peanut-butter-and-jelly-sandwich-recipe/'],
    'Scrambled Tofu': ['https://www.simplyrecipes.com/recipes/scrambled_tofu/'],
    'Vegetable Omelette': ['https://www.allrecipes.com/recipe/26460/vegetable-omelet/'],
    'Pasta with Garlic and Olive Oil': ['https://www.simplyrecipes.com/recipes/pasta_with_garlic_and_oil/'],
    'Cereal with Milk': ['https://www.foodnetwork.com/recipes/cereal-with-milk-recipe/'],
    'Fried Rice': ['https://www.simplyrecipes.com/recipes/fried_rice/'],
    'Tomato Soup': ['https://www.allrecipes.com/recipe/39544/garden-fresh-tomato-soup/'],
    'Mashed Potatoes': ['https://www.simplyrecipes.com/recipes/mashed_potatoes/'],
    'Classic BLT Sandwich': ['https://www.allrecipes.com/recipe/236896/classic-blt/'],
    'Oatmeal': ['https://www.allrecipes.com/recipe/220520/morning-glory-oatmeal/'],
    'Chicken Noodle Soup': ['https://www.simplyrecipes.com/recipes/chicken_noodle_soup/'],
    'Greek Salad': ['https://www.loveandlemons.com/greek-salad/'],
    'Cake': ['https://www.allrecipes.com/recipe/17481/simple-white-cake/'],
    'Brownies': ['https://www.inspiredtaste.net/24412/cocoa-brownies-recipe/'],
    'Meatballs': ['https://www.iheartnaptime.net/meatball-recipe/#recipe']
}
